redhat-cop/operator-utils

- .travis.yml
- Makefile
- README.md
added travis
improved docs
disabled helm
> added badges

- build/Dockerfile
> fixed operator name in docker file

- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
> fix race condition

- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
- pkg/util/lockedresourcecontroller/locked-resource-manager.go
> fix idempotentcy on deletion

- README.md
- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
- pkg/util/lockedresourcecontroller/locked-resource-manager.go
- pkg/util/lockedresourcecontroller/resource-reconciler.go
- test/failing-enforcing_cr.yaml
fixed some bugs on failures
at creation and termination of the
enforcing reconcilers
> manage failures at creation and termination

- deploy/crds/example.io_enforcingcrds_crd.yaml
- deploy/crds/example.io_enforcingpatches_crd.yaml
- deploy/crds/example.io_mycrds_crd.yaml
- deploy/crds/example.io_templatedenforcingcrds_crd.yaml
- pkg/controller/enforcingcrd/enforcingcrd_controller.go
- pkg/controller/enforcingpatch/enforcingpatch_controller.go
- pkg/controller/templatedenforcingcrd/templatedenforcingcrd_controller.go
- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
- pkg/util/lockedresourcecontroller/locked-resource-manager.go
- pkg/util/predicates.go
added ability to create per namespace watchers
fixed status update error message on race condition
> adding multinamespace cache

- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
- pkg/util/lockedresourcecontroller/locked-resource-manager.go
> added ability to pass rest config to stoppable manager

- README.md
- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
- pkg/util/lockedresourcecontroller/locked-resource-manager.go
- pkg/util/templates.go
and other validation bug fixes...
> Fix cache initialization

- README.md
- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
- pkg/util/lockedresourcecontroller/locked-resource-manager.go
- pkg/util/lockedresourcecontroller/lockedresource/locked-resource.go
> fix resource sameness

- pkg/util/apis/key.go
- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
> fixed possible race condition on resource update

- pkg/controller/templatedenforcingcrd/templatedenforcingcrd_controller.go
Adding the correct signature for a method call to the templating function.
> Add Correct Signature

- go.mod
- go.sum
- pkg/util/apis/key.go
- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
- pkg/util/lockedresourcecontroller/locked-resource-manager.go
- pkg/util/lockedresourcecontroller/lockedpatch/locked-patch.go
- pkg/util/lockedresourcecontroller/lockedresource/locked-resource.go
- pkg/util/lockedresourcecontroller/patch-reconciler.go
- pkg/util/lockedresourcecontroller/resource-reconciler.go
- pkg/util/templates.go
aligned logging to the new sdk standard
changed template to use unstructured.UnmarshalJSON
> aligned logging to the new sdk standard

- controllers/enforcingcrd_controller.go
- controllers/enforcingpatch_controller.go
- controllers/templatedenforcingcrd_controller.go
- go.mod
- pkg/util/apis/enforcing-reconciler-status.go
- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
- pkg/util/lockedresourcecontroller/locked-resource-manager.go
- pkg/util/lockedresourcecontroller/resource-reconciler.go
> fix more typos

- README.md
> Update readme to match signature

- .github/workflows/pr.yaml
- .github/workflows/push.yaml
- Dockerfile
- go.mod
> Upgrade to golang 1.15

- README.md
- pkg/util/reconciler.go
> add requeueAfter variants, add convenience function. Fixes #48

- README.md
> add badge for godcs. Fixes #57

- main.go
- pkg/util/lockedresourcecontroller/enforcing-reconciler.go
- pkg/util/lockedresourcecontroller/locked-resource-manager.go
- pkg/util/lockedresourcecontroller/patch-reconciler.go
- pkg/util/lockedresourcecontroller/resource-reconciler.go
- pkg/util/reconciler.go
> added unit test-friendly constructor for ReconcilerBase

- Dockerfile
> fixed nonroot

- controllers/suite_test.go
> Drop duplicated code.
